//EXAMPLE ON SINGLE LEVEL INHERITANCE
public class EX1								//MAIN CLASS
{
	public static void main(String []arg)
	{
		TWO ob=new TWO();						//CREATING AN OBJECT AND ASSIGNING A REFERENCE TO THE OBJECT
		ob.GREET();								//CALLING A METHOD FROM ANOTHER CLASS USING OBJECT
		ob.WISH();								//CALLING A METHOD FROM ANOTHER CLASS USING OBJECT
	}
}